name: Generate Snake Animation 🐍

on:
  schedule:
    - cron: "0 0 * * *"  # daily at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Snake SVG
        uses: athul/snk@main  # Fork with full customization support
        with:
          github_user_name: sheersh01
          outputs: |
            ./dist/github-contribution-grid-snake.svg
          # 👇 Customization options for Dark Cyberpunk Theme:
          snake_color: '#00FF00'          # Neon Green Snake
          background_color: '#1A1A1A'    # Dark background
          color_snake: '#00FF00'          # Snake outline (neon green)
          color_dots: '#6600FF, #9933FF'  # Purple gradient dots
          speed: 1                        # Moderate speed
          grid_size: 13                   # Grid size (adjustable)
          stroke: 2                       # Snake thickness

      - name: Push snake svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
